### ISSUE TITLE
Organizationの管理者を複数人体制にする

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#1208]
Organizationの管理者を複数人体制にする

**背景や動機**
2023-07-11 に5ch.netのDATファイルへのアクセスが再び解放されました。
この影響でJDimで5chの利用が容易になりましたが改めてプロジェクトの活動について考えています。

現在は、私 @ma8ma が中心となってプロジェクトの管理やメンテナンスを行っていますが、
不慮の事態が起こり長期間活動できなくなる、あるいは戻ってこない場合がリスクになると思います。
JDimproved(Organization)に活動中のownerが一人しかいない場合、その人がいなくなるとプロジェクトの管理ができなくなる可能性があります。

プロジェクトが孤立して放棄するしかない事態を避けるため協力をお願いしたいことがあります。

**解決方法**
JDimproved Organizationのowner(管理者)を複数人体制にしてプロジェクトの所有・アクセス権が失われないようにします。
恐れ入りますが、複数人にするownerの一人を @mtasaka さんにお願いできないでしょうか。

@mtasaka さんに頼みたいことは私 @ma8ma がいなくなり戻ってこないときの対応です。
具体的にはリポジトリのコミットが更新されなくなりリリースや活動休止の計画もお知らせも無いまま半年以上経過したときは
差し障りのない範囲でowner権限が必要なプロジェクトの管理をお願いしたく存じます。

* プロジェクトの活動停止をお知らせする
* メンテナー @ma8ma に連絡を取る (GitHubのコメントやEメール)
* 連絡がつかないときは新しいメンテナーを募集する

私自身がプロジェクトから離れると決心したときは活動休止や引き継ぎを果たしてから去るつもりですが
プロジェクトから突然いなくなるリスクはゼロではないのでもしもの計画を立てておきたい所存です。

**Comment by mtasaka** [comment]
分かりました。（とは言っても owner の権限が何かあんまり良く分かってないですが）何かお手伝いできる事（とかもしもの場合、新しいメンテナを探すこととか）があれば、是非協力します。

**Comment by ma8ma** [comment]
@mtasaka ありがとうございます。

owner権限を持つユーザーはorganizationの設定でかけられる制限をすべて無視して変更やコミットを行うことができます。
organizationのメンバーの追加・削除・権限変更もowner権限なのでownerが不在になると立ち行かなくなります。

**Comment by mtasaka** [comment]
今ownerに追加されていることを確認しました

**Comment by ma8ma** [comment]
平時であればメンテナーを続けていく所存ですが何かあって続けられないことがあれば辞めることを事前にお話し相談します。
不慮のことで復帰できなかったときはお手数をおかけしますがお願いいたします。

**Comment by mtasaka** [comment]
了解しました。

**Comment by ma8ma** [comment]
issueを閉じます
