### ISSUE TITLE
X11 マルチディスプレイ環境でモニタの位置オフセットが考慮されず、ポップアップの表示位置がおかしい

### ISSUE THREAD

**Issue by mokeke-maru** [JDimproved/JDim#1489]
**バグの説明**

マルチモニタ環境でX11を使用し、モニタの位置にオフセットがある場合、ポップアップメニューの位置がおかしいです。

**再現の方法**

1. マルチディスプレイ環境でX11を使用
1. モニタの位置にオフセットを設定する
   ```
   xrandr --output "HDMI-0" --pos "0x0" --output "DP-0" --pos "3440x0"
   ```
1. オフセットの効いたモニタ(ここではDP-0)上でJDimを起動
1. ポップアップメニューがモニタからはみ出して表示される

オフセットの効いていないモニタ(HDMI-0)では正しく表示されます。

**やりたかったこと・期待する結果**

- ポップアップメニューがマウスカーソルの位置に応じて適切な位置に表示される
- モニタのオフセット設定に関わらず、各モニタで正しくポップアップが表示される

**スクリーンショット**

![image](https://github.com/user-attachments/assets/5b460309-961e-47e0-aff2-085323b98c63)

**動作環境**

```
[バージョン] JDim 0.13.0-beta20241221(git:056d34bf3a:M)
[ディストリ ] Arch Linux (x86_64)
[パッケージ] バイナリ/ソース( <配布元> )
[ DE／WM ] (unknown) (X11)
[　gtkmm 　] 3.24.9
[　glibmm 　] 2.66.7
[　TLS lib　] GnuTLS 3.8.8
[オプション ] '--with-native'
[ そ の 他 ] 
```

WMはi3-wmを使用しています。

```
Screen 0: minimum 8 x 8, current 7280 x 2160, maximum 32767 x 32767
HDMI-0 connected 3440x1440+0+0 (normal left inverted right x axis y axis) 797mm x 333mm
DP-0 connected primary 3840x2160+3440+0 (normal left inverted right x axis y axis) 600mm x 330mm
```

**追加の情報**

x方向だけですが、ジオメトリ情報を元にオフセットを考慮すると正常に表示されました。

```cpp
  Gdk::Rectangle monitor_geometry;
  monitor->get_geometry( monitor_geometry );

  const int x_mouse_local = x_mouse - monitor_geometry.get_x();

  int x_popup;
  if( x_mouse_local + m_mrg_x + width_popup <= width_desktop ) x_popup = x_mouse + m_mrg_x;
  else x_popup = monitor_geometry.get_x() + MAX( 0, width_desktop - width_popup );
```

![image](https://github.com/user-attachments/assets/bcf431a8-17c1-442f-8298-5a051281287f)

**Comment by ma8ma** [comment]
@mokeke-maru さん、詳細なバグ報告をありがとうございます。

現在、私の環境ではマルチディスプレイを用意できないため、いくつか確認させていただきたい点があります。

1. 最近、X11でのポップアップ表示位置に関する修正を行いました (詳細はこちら: https://github.com/JDimproved/JDim/pull/1482 )。この修正の前後で、ポップアップの表示位置がどのように変わったか、ご存じでしたら教えていただけますか。

2. ジオメトリ情報を基にX方向で補正が効いたとのことですが、Y方向についても同様の補正を試みた場合、どのような表示や結果になりましたか。試された内容があれば、ぜひご教示ください。

お手数をおかけしますが、参考までに、コンソールで #1482 を取り消してビルドする方法を以下に示します。

```sh
# リポジトリをクローン
git clone --depth 1 https://github.com/JDimproved/JDim jdim-test
cd jdim-test
# コミットの取り消し
git revert -n ec06becf1ffcb47a88e8f250c215b6a61ec95da1
# ビルド
meson setup build
ninja -C build
# ポップアップのテスト: 実行後、問題の再現手順に従い、表示位置に変化があるか確認してください。
./build/src/jdim
# リポジトリの片付け
cd ../
rm -rf jdim-test
```

引き続き、必要な情報があれば教えていただけると助かります。よろしくお願いいたします。

**Comment by mokeke-maru** [comment]
ありがとうございます、情報が抜けていましたが #1482 のマージで再現するようになったので報告させて頂きました。

ポップアップ位置を判定するのに使用しているマウス座標の値がグローバルなままのようなので、作業領域で補正する必要がありそうです。

> 最近、X11でのポップアップ表示位置に関する修正を行いました。この修正の前後で、ポップアップの表示位置がどのように変わったか、ご存じでしたら教えていただけますか。

右に位置するモニタ(DP-0)で常用していたため、私の環境では今まで問題にならなかっただけのようです。  

原点にある左のモニタ(HDMI-0)では #1482 の有無でPR通りの挙動が確認できました。

``` log
    PopupWin::slot_resize_popup : x = 2653 y = 995 w = 889 h = 213 -- #1482  取り消し, はみでる
    PopupWin::slot_resize_popup : x = 2551 y = 994 w = 889 h = 213 -- HEAD  はみでない
```

> ジオメトリ情報を基にX方向で補正が効いたとのことですが、Y方向についても同様の補正を試みた場合、どのような表示や結果になりましたか。試された内容があれば、ぜひご教示ください。

Y方向にオフセットのある環境でも同様に再現する筈なので検証してみました。 
mokeke-maru/JDim@b6563e5dcfdfa5f13f4c6cd30e236c4f5c6e0262

- DP-0 (3840x2160+3440+0)

``` log
    PopupWin::slot_resize_popup : x = 6064 y = 1748 w = 943  h = 179  -- 上に表示
    PopupWin::slot_resize_popup : x = 5993 y = 314   w = 1005 h = 474  -- 下に表示
    PopupWin::slot_resize_popup : x = 5970 y = 0        w = 1310 h = 1077 -- スペースは無いが上に表示
    PopupWin::slot_resize_popup : x = 5970 y = 442   w = 1310 h = 1718 -- 下
```

- HDMI-0 (3440x1440+0+0)

``` log
    PopupWin::slot_resize_popup : x = 2407 y = 1029 w = 943  h = 179
    PopupWin::slot_resize_popup : x = 2279 y = 543   w = 1064 h = 574
    PopupWin::slot_resize_popup : x = 2330 y = 0        w = 1110 h = 1034
    PopupWin::slot_resize_popup : x = 2330 y = 540   w = 1110 h = 900
```

- DP-0をY方向へ移動

``` bash
    $ xrandr --output "HDMI-0" --pos "0x0" --output "DP-0" --pos "0x1440"

    Screen 0: minimum 8 x 8, current 3840 x 3600, maximum 32767 x 32767
    HDMI-0 connected 3440x1440+0+0 (normal left inverted right x axis y axis) 797mm x 333mm
    DP-0 connected primary 3840x2160+0+1440 (normal left inverted right x axis y axis) 600mm x 330mm
```

- DP-0 (3840x2160+0+1440)

``` log
   PopupWin::slot_resize_popup : x = 2648 y = 3174 w = 943   h = 179
   PopupWin::slot_resize_popup : x = 2562 y = 1753 w = 1005 h = 474
   PopupWin::slot_resize_popup : x = 2530 y = 1440 w = 1310 h = 1063
   PopupWin::slot_resize_popup : x = 2530 y = 1880 w = 1310 h = 1720
   ```

- HDMI-0 (3440x1440+0+0)

``` log
   PopupWin::slot_resize_popup : x = 2448 y = 1011 w = 943   h = 179
   PopupWin::slot_resize_popup : x = 2367 y = 545   w = 1064 h = 574
   PopupWin::slot_resize_popup : x = 2330 y = 0        w = 1110 h = 1022
   PopupWin::slot_resize_popup : x = 2330 y = 533   w = 1110 h = 907
```

**Comment by ma8ma** [comment]
検証ありがとうございます。
ご提示いただいたコミット https://github.com/mokeke-maru/JDim/commit/b6563e5dcfdfa5f13f4c6cd30e236c4f5c6e0262 について、シングルディスプレイ環境で正常に動作することを確認いたしました。現時点での検証結果から判断する限り、この修正でマルチディスプレイ環境でもXY方向の補正が可能であれば、マージを進めたいと考えております。問題点や懸念がございましたら、お知らせいただけますと幸いです。

また、@mokeke-maru さんの修正を参考に、Wayland環境のポップアップ配置ロジックをX11環境にも適用するパッチを作成しました。お時間のある際にぜひお試しいただければと思います。

https://github.com/ma8ma/JDim/pull/87

このパッチは親ウィンドウの左上を原点としてポップアップの位置を決定し、2つのウィンドウの相対的な座標で配置します。これにより、モニターの画面領域を考慮した座標計算がY方向のみで済むようになります（マウスポインターの上と下どちらにポップアップを配置するかの判断など）。
これが正常に動作する場合、WaylandとX11で分かれていた処理をまとめることができます。

以下のコマンドで、パッチ適用済みのソースコードを取得できます。
```
git clone --depth 10 -b test-apply-wayland-popup-positioning-logic-to-x11 https://github.com/ma8ma/JDim.git jdim-test
```

お手数をおかけしますが、ご確認のほどよろしくお願いいたします。

**Comment by mokeke-maru** [comment]
ご確認ありがとうございます。

少なくとも私の環境では X11 マルチディスプレイ環境でシングルディスプレイ環境と相違なくポップアップ画面が表示される事を確認できました。
念の為、いくつか他のWMや3ディスプレイ環境でも検証致しました。

また @ma8ma さんのご提案して頂いたパッチにつきましても`gdk_window_move_to_rect`によるポップアップ画面の正常な表示を確認できました。


御対応ありがとうございました。

**Comment by ma8ma** [comment]
@mokeke-maru さん
詳細な検証、本当にありがとうございます！特に様々なWMや3ディスプレイ環境での検証結果は、非常に貴重な情報です。
追加でご提案したパッチについても、動作確認していただき大変助かります。

いただいた結果を踏まえ、X11とWaylandの処理をまとめる https://github.com/ma8ma/JDim/pull/87 をさらにブラッシュアップし、masterブランチへのマージを進めさせていただきます。

今回のバグ報告と迅速なご対応、誠にありがとうございました。今後とも、どうぞよろしくお願いいたします。

**Comment by ma8ma** [comment]
masterブランチに修正をマージしました。 #1491
バグ報告とパッチのご提供をいただき、改めてお礼を申し上げます。
