### ISSUE TITLE
本家JD projectとの区別について

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#15]
### 要約 (2024-07-07)
* 名前はJDimに[決定](https://github.com/JDimproved/JDim/issues/15#issuecomment-455791506)
* GitHub Organization https://github.com/JDimproved を[設立](https://github.com/JDimproved/JDim/issues/15#issuecomment-456233875)
* バージョン`0.12.0`が[リリース](https://github.com/JDimproved/JDim/releases/tag/JDim-v0.12.0)された。
* [本家版](https://jd4linux.osdn.jp/manual/289/)をもとにオンラインマニュアルを作成し[公開](https://jdimproved.github.io/JDim/)した
* freedesktop.orgの標準への対応を進めた
  #106 
  #107
  #108)
* ロゴを[修正][fix-logo-svg]した [![new-logo16]][fix-logo-svg]
* GTK2版のサポートを終了した (#229)
* プロジェクトのwebサイトは作成されていない
* [RFC 0013] が承認され、パッチや修正のライセンスは GPL-2.0-or-later または寛容なライセンスで受け入れるようになった

[RFC 0013]: https://github.com/JDimproved/rfcs/blob/master/docs/0013-introduce-license-gpl-2.0-or-later.md
[new-logo16]: https://raw.githubusercontent.com/JDimproved/JDim/43c7bc6b26bd8e947594d445dd72c8c46d56f69e/src/icons/jd16.png
[fix-logo-svg]: https://github.com/JDimproved/JDim/blob/43c7bc6b26bd8e947594d445dd72c8c46d56f69e/src/icons/jd96.png

---

yama-natuki/JD は本家 (https://osdn.net/projects/jd4linux/) にない機能(5ch、C++11、GTK+3)を追加(予定)しているのでJD projectとgithubのJDは何らかの区別する点があるほうがよいと考えています。

そこで分かりやすいところとしてソフトウェア名と著作者の表示の更新を提案します。
私(@ma8ma)はGTK3対応ついでに更新してしまうほうがタイミングがいいかなと思っています。

#### ソフトウェア名の更新
* 同じまま
* 変更しないがREADMEやAboutダイアログに本家と区別するためのカッコ書きや断り書きを入れる
* 変更する

#### 著作者の表示の更新
* そのまま
* パッチ作成者の個人名orアカウント名を加える
* パッチ作成者に確認を取ってJD projectのようにグループをつくる

**Comment by yama-natuki** [comment]
すでに本家の開発は停止しているので、ma8maさんが積極的に開発を続ける意思があるのでしたら区別を付けるために名称変更も良いのではないかなと思います。

**Comment by ma8ma** [comment]
> 積極的に開発を続ける意思

自分でJDを使っている間はやりたいと考えています。
ただ、GTK中心の修正だったので掲示板の仕様が変わったときなど対応できるかどうか不明です…

名称変更したとき@yama-natukiさんにリポジトリの変更をPRなどでお願いしてもよろしいですか。
それかgithubのorganizationだとリポジトリの編集に加わってお手伝いできると思います。

**Comment by ma8ma** [comment]
gtk3対応ための修正が一段落ついたので名称を募集します。(はっきり決めてませんが1-2週間の間？)
基本方針はJDを調べる人が自然に見つける感じが一番なので"JD"からまったく別にするつもりはないです。(例えばVim→NeovimのようにJD→NeoJDとJDを残す)
ただ、JD2のような本家プロジェクトと関係がある印象の名前は避けたいと思います。

**Comment by henrich** [comment]
こんにちは、Debianでjdのパッケージメンテをやってます（or ました。残念ながらupstreamの動きがないので…）。Ubuntuの[launchpadでのbug report](https://bugs.launchpad.net/ubuntu/+source/jd/+bug/1799044)でこちらを知りました。

別名称の候補は出てきていますか？候補が決まれば、こちらをパッケージにさせて頂いて旧jdのパッケージは削除しようかな、と思っています。

**Comment by ma8ma** [comment]
@henrich まだ決まってないですが名称の候補はこの辺です https://mao.5ch.net/test/read.cgi/linux/1540656394/276-303
今は他のことを優先しようとしているのですがdebian busterはフリーズ日が近いですか？とりあえず5chで挙げられた候補をピックアップして商標に使われていないか検索してまとめてみます。

**Comment by henrich** [comment]
@ma8ma リンクありがとうございました。

そうですね、[最初のフリーズ（transition freeze=ライブラリバージョンの更新禁止）は1/12に始まりました](https://release.debian.org/buster/freeze_policy.html)。2/12のsoft freeze時点でtestingに入っていないといけないので、逆算すると…実はそろそろUploadしていないと厳しかったりします（新しいバイナリパッケージは[NEW queue](https://ftp-master.debian.org/new.html)と呼ばれるアーカイブ管理者の審査待ちがあって、これが最短で数時間〜最長で数ヶ月というものなのです）。

busterに間に合わなかった場合はbuster-backportsに放り込むという形で対応しようかな、と思っています。

**Comment by ma8ma** [comment]
@henrich それなら名称を決めればいけそうですね。候補はまとめるとしてどうやって決めるか…ここで参加者に聞くか、5chにレスするか、yama-natuki氏に頼むか。

**Comment by yama-natuki** [comment]
私は何もしていないので、主体となって開発している @ma8ma  さんの独断で決定して良いと思いますよ。

**Comment by henrich** [comment]
@ma8ma お願いします！ :-)

**Comment by ma8ma** [comment]
5chに挙げられた候補が商標に使われていないか[tmview][tmview]で検索した結果が下の表です。合わせてweb検索もしてみました。

[tmview]: https://www.tmdn.org/tmview/welcome

名称 | レスにあった補足 | tmviewヒット数[1] | web検索[2]
--- | --- | --- | ---
JD (参考) | JaneDoeの頭文字から | 69/497 | 企業(-software)
OL | JKだとバージョンが逆行した感じになる | 54/176 | 企業(-software)、htmlタグ
JDim | JD improved | N/A |
JDM | JDもどき | 24/79 | 企業(-software)
JKJD | | N/A |
JDi, JDI | ジェダイと読む, 女子大学院生 | 23/50 | 企業(-software)
JJHJYJSJC | | N/A |
NSJD | | N/A |
NNJD | | N/A |
JaneDoeStyle | | N/A | 5chブラウザ Jane Style
JaneGT | GTKのJane | N/A |
JDD | Dを一つ増やして | 7/12 | 企業(-software)
JDex | JD Extended | 1/1 |
re-JD (rejd) | remodeled JD | N/A (1/7) |
JD-ng (jdng) | | N/A (N/A) |
YAJ (YAJD) | Yet Another JD | 1/3 (N/A) |

[1] tmview検索：is検索＋フィルター([区分9,42][kubun]/無し), N/Aは該当なし
[2] web検索：名称 & (software|browser|2ch)
ヒット数には終了しているものや指定役務がソフトウェアと関係ないものも含まれています。

[kubun]: https://www.jpo.go.jp/shiryou/kijun/kijun2/ruiji_kijun9.htm

まとめ
* web検索で引っかかる似通ったソフトウェアはJane Styleくらい
* ヒット数が多くても指定役務とロゴマークが被らないようにすれば問題ないと思うが確認するのに時間がかかる

**Comment by ma8ma** [comment]
新名称を2019-01-20に決めることにしました https://mao.5ch.net/test/read.cgi/linux/1540656394/410

**Comment by ma8ma** [comment]
JDim (JD improved)に決定しました。 https://mao.5ch.net/test/read.cgi/linux/1540656394/417-418
パッケージ化を踏まえて要点を絞って更新作業を行います。

* 名称と著作者表示
* コードやドキュメントに含まれる情報
* masterブランチへマージ
* バージョン番号
* デフォルト設定
* リポジトリ

### 未解決の部分

#### 名称と著作者表示
* fork元のJD projectを併記する/しない
* JDim のプロジェクト化の有無

#### バージョン番号
オンラインマニュアルのURLにバージョンが含まれているため変更する場合は現行バージョン`289`をハードコーディングする必要がある
* メジャーバージョンをアップ `3.0.0`
* マイナーバージョンをアップ `2.9.0`
* リセット `0.1.0`
* とりあえず変更しない

#### デフォルト設定
デフォルトでは5ch.netにアクセスするがユーザーが追加の設定をしないとスレッドの読み込みができない問題がある
* 現状のまま
* 回避策として板一覧を取得するサーバーを変更する

#### リポジトリ
* 既存の JD のリポジトリを JDim へリネームする
* 新名称への更新に合わせて JDim のリポジトリ, organizationを作成する

**Comment by henrich** [comment]
バージョンは日付だけとかでもいいかもしれません（semverとかも視野に入れるとかなら別ですが、悩まずに済みます）

リポジトリのURLが変わるようであれば、優先度を挙げて頂けるとたすかります。m(_ _)m

**Comment by henrich** [comment]
著作権表記、というか著作権としてはfork元のJD projectも保持している、という状態ですよね。

githubのorganizationにするのはいいんじゃないでしょうか。

**Comment by ma8ma** [comment]
@yama-natuki @henrich 
__バージョン__
バージョニングをどうやっていくのか固まってないので今のところは`0.1.0`にリセットしておきます。semvarについてはそこまで有用じゃないと考えてます。(複数バージョンをメンテナンスするのは厳しい)

__著作権表記__
forkしたソフトウェアがどのようにfork元を表示すればいいのかよく分かりません。
LibreOfficeのAboutダイアログは単独copyrightとforkの説明 (2010年リリースだがOOOの開発者が参加)
```
Copyright © 2000-2016 LibreOffice contributors
LibreOfficeはOpenOffice.orgを元にしています。
```
MATEのAboutダイアログはcopyright列挙 (GNOMEとは関係ない開発者?)
```
Copyright © 1997-2011 GNOME developers
Copyright © 2011 Perberos
Copyright © 2012-2016 MATE developers
```
fork元と開発者の繋がりがない?MATEのようにcopyright列挙で問題ないでしょうか。
```
Copyright © 2006-2015 JD project
Copyright © 2017-2019 yama-natuki
# orgを立ち上げるなら
Copyright © 2019 JDim project?
```

__organization__
やるならyama-natuki/JDをtransfer ownershipするのが都合がいいと思います。transferを使ったことがありませんが下の手順でyama-natuki/JDへのURLはxxx/JDimへ上手くリダイレクトするでしょうか？
1. organization xxxを作成
2. yama-natuki/JDをtransferしてxxx/JDを作る
3. xxx/JDをxxx/JDimにリネームする
4. xxx/JDimをforkしてyama-natuki/JDimを作り個人リポジトリを復元する (可能か分からない)

**Comment by yama-natuki** [comment]
作ってみましたが、
https://github.com/JDimproved
これオーナーを @ma8ma さんに変更できますかね？
できない場合はもう一度organization作成かな？

ちなみにプロジェクト名は「JDim」はすでに使われていて駄目でした。

**Comment by ma8ma** [comment]
JDimprovedに入りました。JDimに更新するPRを用意して出します。
@yama-natuki さんの公開があってJDが利用しやすい状態で続いていたのでオーナーはyama-natukiさんがいいと私は思います。 :sparkles:

**Comment by ma8ma** [comment]
@yama-natuki #24 の更新ありがとうございます。

@henrich @mtasaka @naniwaKun
ディストリのJDimパッケージ化で気になることが一つ、上のコメントで触れましたが初期設定では5chのスレッドを読み込むことができません。一言で言えばヘビーユーザー向けですが問題ないでしょうか？
([5ch.net 専用ブラウザの開発者の皆さまへ](https://developer.5ch.net/)を読むと回避策への案内はやらないほうが無難かなと思っています)

**Comment by naniwaKun** [comment]
@ma8ma 案内無しで問題ないかと思います。インストール方法と明確に区別しておいたほうがいいです。

**Comment by ma8ma** [comment]
@naniwaKun 0.1.0より後になりますが[オンラインマニュアル][manual]をgithubへ移植し、板一覧を取得するサーバーの変更とプロキシの設定の説明を追加できないか考えています。

初期設定を2ch.scやopen2chなどに変更して"スレッドを読み込める"状態にする案も一応あります。(新規ユーザーを余計に混乱させるかもしれないので判断が難しいです)

[manual]: http://jd4linux.osdn.jp/manual/289/

**Comment by naniwaKun** [comment]
@ma8ma 
2ch.scやopen2chはあまり使われていないので2ch、5chにかかわらず他の掲示板でも良いかもしれません。
あと、Archlinuxのパッケージ名の問題ですが、現在は「jd-gtk3」になっています。名称変更に伴って変更しようかと思うのですが、「jdim」で良いでしょうか？それとも「jdim-gtk3」になりますでしょうか？gtk2の保守の問題になりますが、どうしておきましょう？

**Comment by ma8ma** [comment]
@naniwaKun Archlinuxでgtk2の扱いがどうなっているのか分かりませんがjdimで大丈夫だと思います。jdim更新が一段落しましたらJDimprovedにgtk3版のPRを出します。それまではma8maのgtk3-previewブランチを更新しますのでよろしくお願いいたします。

**Comment by naniwaKun** [comment]
@ma8ma なるほど承知いたしました。様子見ながら変更作業をして変更できたらお知らせします。

**Comment by ma8ma** [comment]
@yama-natuki 更新ありがとうございます。
プロジェクトの区切りとして休眠しているmasterブランチをJDimのデフォルトブランチとして使いたいと考えているのですが、testのREADME.mdを微修正してmasterへPRを提出してもよろしいでしょうか。

@henrich 私の考えている範囲で時間がかからない修正はやれたと思います。現状でパッケージ化の課題がありましたらご教示いただければと存じます。
#### バージョン0.1.0時点では修正しない箇所(案)
* ロゴマークの更新
* オンラインマニュアルの作成
* プロジェクトのwebサイトの作成
* GTK3対応の追加 (https://github.com/JDimproved/JDim/issues/7)

**Comment by yama-natuki** [comment]
急ぎのPRがなければ今月末でイニシャルリリースタグを付けようかなと思います。

もうオリジナルのJDを維持する必要もないので、masterブランチをJDimのデフォルトブランチとして復活させてもいいかなと思います。

**Comment by henrich** [comment]
debianで[パッケージ申請をしてバグ番号を取得](https://bugs.debian.org/9206)しておきました。タグが打たれたらビルドしてみます。

**Comment by yama-natuki** [comment]
@henrich ありがとうございます。
30か31日にタグを打ちます。

**Comment by yama-natuki** [comment]
タグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.1.0

**Comment by henrich** [comment]
Debianパッケージの進捗ですが、ftpmasterによる審査待ちです。
https://ftp-master.debian.org/new.html

**Comment by henrich** [comment]
unstableに入りました。数日後にtesting（現在はbuster）に落ちます。
そうしたらREADMEとかいろいろ書き換えます。
https://tracker.debian.org/pkg/jdim

**Comment by ma8ma** [comment]
バージョン`0.2.0`をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.2.0

**Comment by ma8ma** [comment]
ロゴを更新しました [![logo48]][logo-svg]

[logo48]: https://raw.githubusercontent.com/JDimproved/JDim/bd5acdf30b87803d8ff5a6a7b283d2c0f18e2ba8/src/icons/jd48.png
[logo-svg]: https://github.com/JDimproved/JDim/blob/bd5acdf30b87803d8ff5a6a7b283d2c0f18e2ba8/jdim.svg

**Comment by ma8ma** [comment]
バージョン0.3.0をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.3.0

**Comment by ma8ma** [comment]
バージョン`0.4.0`をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.4.0

testブランチを削除しました。

**Comment by ma8ma** [comment]
バージョン`0.5.0`をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.5.0

**Comment by ma8ma** [comment]
バージョン`0.6.0`をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.6.0

**Comment by ma8ma** [comment]
バージョン`0.7.0`をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.7.0

**Comment by ma8ma** [comment]
バージョン0.8.0をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.8.0

**Comment by ma8ma** [comment]
バージョン0.9.0をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.9.0

**Comment by ma8ma** [comment]
バージョン0.10.0をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.10.0

**Comment by ma8ma** [comment]
バージョン0.10.1をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.10.1

**Comment by ma8ma** [comment]
バージョン0.11.0 をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.11.0

**Comment by ma8ma** [comment]
[RFC 0013] が承認され、パッチや修正のライセンスは GPL-2.0-or-later または寛容なライセンスで受け入れるようになりました。

[RFC 0013]: https://github.com/JDimproved/rfcs/blob/master/docs/0013-introduce-license-gpl-2.0-or-later.md

**Comment by ma8ma** [comment]
バージョン0.12.0 をタグ付けしました。
https://github.com/JDimproved/JDim/releases/tag/JDim-v0.12.0

**Comment by ma8ma** [comment]
JD projectから別れてJDim projectを立ち上げてから時間が経ち、このissueを開いておく意味も薄れてきたと考えています。
そこで、README.mdにここへのリンクを追加してissueを閉じたいと思います。

**Comment by ma8ma** [comment]
これまでのご協力と取り組みにお礼申し上げます。このissueは一旦クローズとさせていただきますが、今後も更新を進めていきますので引き続きよろしくお願いいたします。
