### ISSUE TITLE
スレタイ検索用のメニュー項目名とかに長い文字列を指定すると変なことになる

### ISSUE THREAD

**Issue by mtasaka** [JDimproved/JDim#180]
Fedora 31 (gcc バージョン 9.2.1 20190827 (Red Hat 9.2.1-1) (GCC))でコンパイルして、一通り警告を確認してみましたが、以下の警告が出ています。

```
In function 'char* strncpy(char*, const char*, size_t)',
    inlined from 'CONTROL::KeyConfig* CONTROL::get_keyconfig()' at controlutil.cpp:50:16:
/usr/include/bits/string_fortified.h:106:34: warning: 'char* __builtin_strncpy(char*, const char*, long unsigned int)' specified bound 64 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In function 'char* strncpy(char*, const char*, size_t)',
    inlined from 'CONTROL::KeyConfig* CONTROL::get_keyconfig()' at controlutil.cpp:51:16:
/usr/include/bits/string_fortified.h:106:34: warning: 'char* __builtin_strncpy(char*, const char*, long unsigned int)' specified bound 64 equals destination size [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

実際「WEB検索用のメニュー項目名」や「スレタイ検索用のメニュー項目名」に長い文字列を指定すると（そんなことをする人は滅多にいないと思いますが）、再起動した後各々の表示が変なことになっています（次のメモリ領域と結合したような文字列が表示される）。細かい問題ですが。

**Comment by mtasaka** [comment]
例えば、 

https://mtasaka.fedorapeople.org/Bugfix/jdim/20200203-134833-jd-setting-long-search-title.png  

こんな感じで設定すると、

https://mtasaka.fedorapeople.org/Bugfix/jdim/20200203-134935-jd-result-long-search-title.png

こんな感じになります。（保証外とは言っていますが）

**Comment by mtasaka** [comment]
#181 で一応警告も消えます（ただ、gccの-Wstringop-の警告は面倒臭くて、後のバージョンで再発するかも知れませんが）

**Comment by ma8ma** [comment]
グローバル変数の固定長バッファにユーザーの入力をコピーしているのが嫌な感じします…
グローバル変数にコピーせず、`CONTROL::get_label()`に条件を追加して直接返すようにするのはどうでしょう

https://github.com/JDimproved/JDim/blob/c9d9ec65c4acb06a126aecacdf4b722660961f85/src/control/controlutil.cpp#L347-L354

を下のように
```cpp
// std::string::substr()を使って適当な長さで切ることもできる
std::string CONTROL::get_label( const int id )
{
    if( id < CONTROL::COMMONMOTION || id >=  CONTROL::CONTROL_END ) return std::string();
    else if( id == CONTROL::SearchWeb ) return CONTROL::get_menu_search_web();
    else if( id == CONTROL::SearchTitle ) return CONTROL::get_menu_search_title();

    return CONTROL::control_label[ id ][ 1 ];
}
```

それかバッファを`std::string`にして固定長の問題を無くしてしまうか
比較するとメモリ使用量が増えます


```cpp
// src/control/controllabel.h
struct ControlLabel
{
    std::string name;
    std::string label;
};

ControlLabel control_label[] = {
    { "name", "label" }, // Small String Optimization に期待！
    /* ... */
};
```

**Comment by mtasaka** [comment]
そうですね... 「グローバル変数にコピーせず、``CONTROL::get_label()``に条件を追加して直接返すようにする」という案でいいような気がしました（もとのグローバル変数が他に使われているところがないか、確認してませんが）

**Comment by ma8ma** [comment]
ラベルの中でweb検索とスレタイ検索だけカスタマイズできるのが正直扱いに困ってます
いろいろ考えると @mtasaka さんのパッチ(#181)で手堅いと思いますし
あとはラベルを固定してカスタマイズ不能にする方法がありました、これなら楽です:stuck_out_tongue_closed_eyes:

**Comment by mtasaka** [comment]
多分「google以外で検索したい人もいるだろうから、その場合は『google検索』というのを変えられるようにしておこう」とかそういう事だと思います。個人的には #181 で取り敢えず（私にとっては）充分です。

**Comment by ma8ma** [comment]
そうですね、私も現状で大丈夫です
英語対応とかでラベルの変更が不可避になる状況もあると思いますがそれはそのときで
