### ISSUE TITLE
Css_Manager::create_textnode で警告が出る

### ISSUE THREAD

**Issue by mtasaka** [JDimproved/JDim#182]
Css_Manager::create_textnode 、 というより https://github.com/JDimproved/JDim/blob/c9d9ec65c4acb06a126aecacdf4b722660961f85/src/cssmanager.cpp#L665 で

```
    inlined from ‘CORE::DOM* CORE::Css_Manager::create_textnode(const char*)’ at cssmanager.cpp:665:12:
/usr/include/bits/string_fortified.h:106:34: 警告: ‘char* __builtin_strncpy(char*, const char*, long unsigned int)’ output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
  106 |   return __builtin___strncpy_chk (__dest, __src, __len, __bos (__dest));
      |          ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cssmanager.cpp: メンバ関数 ‘CORE::DOM* CORE::Css_Manager::create_textnode(const char*)’ 内:
cssmanager.cpp:656:21: 備考: length computed here
  656 |     int lng = strlen( text );
      |               ~~~~~~^~~~~~~~
```
という警告が出ていて、確かに警告の通り ``tmpdom->chardat``がこのままだとnull-terminateされません。  
現状 https://github.com/JDimproved/JDim/blob/c9d9ec65c4acb06a126aecacdf4b722660961f85/src/jdlib/heap.cpp#L58 でmemsetされているので大丈夫なように見えます。  

修正としては、``strncpy( tmpdom->chardat, text, lng );`` を単に ``strncpy( tmpdom->chardat, text, lng + 1 );``にすればよいと思いますが（警告も出なくなる）、cssを使ってないので自信がありません。

**Comment by ma8ma** [comment]
うーん、入力のtextと確保したバッファの長さはstrlen()で計算済、heapクラスでバッファをゼロ初期化しているので警告を出さない関数に変更するのもありかもしれません
`std::memcpy( tmpdom->chardat, text, lng );`

**Comment by mtasaka** [comment]
個人的な感想を言えば、「heapクラスでゼロ初期化している」という別の所のコードを読まないと、``tmpdom->chardat``がnull-terminateされることが（その場のコードからは）分からない、というのは好きではないです。``std::memcpy( tmpdom->chardat, text, lng );``だと、結局最後のnull characterはcopyされないので。警告の趣旨は、「textの最後のnull charaterはコピーされてないけど大丈夫か？」ということなので ( strlen(text)は、textのnull character分は含まない）、``lng + 1``分だけコピーするというほうが個人的には好きです（それか、sprintfを使うとか）

**Comment by ma8ma** [comment]
あー確かに別の場所のコードを見なくても分かるstrncpyが合ってますね。引数を訂正したパッチを試してPRを出します。

余談ですがcssmanagerはheapクラスから直に割当て＋ポインターでつなぐリンクリスト構造からカスタムアロケーターを使ったSTLコンテナに置き換えられないかなあと思ってます。
