### ISSUE TITLE
特定の絵文字(subdivision-flags)が正常に書き込みできない

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#214]
特定の絵文字が正常に書き込みできない不具合がありましたので再現の手順を報告します。

#### 動作環境
`jdim --version`の結果
```
JDim 0.3.0-20200315(git:e6a494ad01)
(c) 2006-2015 JD project
(c) 2017-2019 yama-natuki
(c) 2019-2020 JDimproved project
configure: 'CFLAGS=-g -O2 -fdebug-prefix-map=/home/ma8ma/var/repos/JDim=. -fstack-protector-strong -Wformat -Werror=format-security' 'LDFLAGS=-Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now' 'CPPFLAGS=-Wdate-time -D_FORTIFY_SOURCE=2' 'CXXFLAGS=-Og -pipe -g -fdebug-prefix-map=/home/ma8ma/var/repos/JDim=. -fstack-protector-strong -Wformat -Werror=format-security -Wno-deprecated-declarations -Wp,-D_GLIBCXX_ASSERTIONS -fuse-ld=lld' 'GTEST_SRCDIR=/usr/src/googletest'
```
動作環境のコピペ
```
[バージョン] JDim 0.3.0-20200315(git:e6a494ad01)
[ディストリ ] Ubuntu 19.10 (x86_64)
[パッケージ] バイナリ/ソース( <配布元> )
[ DE／WM ] KDE
[　gtkmm 　] 3.24.1
[　glibmm 　] 2.60.0
[　TLS lib　] GnuTLS 3.6.9
[オプション ] 
[ そ の 他 ] 
```

#### 不具合発生までの手順

1. masterブランチ(e6a494ad0137b66bc8d4320f3bddbefb621bebd4)のGTK3版をビルド・実行する
2. 新規キャッシュディレクトリで起動
   ```
   JDIM_CACHE=$(pwd)/Test_new ./src/jdim
   ```
3. メニューバーの`ヘルプ(H)＞JDサポート掲示板(B)`を選択して書き込みテストのスレッドを開く
4. 書き込みビューを開いて「右クリック→`Insert Emoji`」または「`Ctrl+.`」で絵文字ピッカー(emoji picker)を出す
5. 絵文字ピッカーを使ってEngland、Scotland、Walesの旗を入力しスレッドに書き込む
6. 書き込まれたレスを確認すると旗は黒色になっている
   (e.g. `ttps://jd4linux.osdn.jp/cgi-bin/bbs/test/read.cgi/support/1397047866/153`)

Unicodeに対応した他のスレッドでも確認しています。（ソフトウェア板、プログラム板など）

#### 書き込んだレスの調査
書き込んだスレのプロパティからローカルキャッシュパスをコピーしてDATファイルをエディターで表示すると当該レスの本文は `&#127988;&#65039;&#127988;&#65039;&#127988;&#65039; (以下省略)` となっています。

England、Scotland、Walesの旗の絵文字は[subdivision-flags][sub]と呼ばれる仕組みで WAVING BLACK FLAG (U+1F3F4) に Tag Latin Small Letter (U+E0061 - U+E007A) と Cancel Tag (U+E007F)を組み合わせて表示されます。
例えば[Englandの旗][eng]は `&#127988;&#917607;&#917602;&#917605;&#917614;&#917607;&#917631;` とDATに書き込まれるはずですが正常に変換されていません。

絵文字ピッカーを使わず数値文字参照を打ち込んでスレッドに書き込むと正常に表示されました。
(e.g. `ttps://jd4linux.osdn.jp/cgi-bin/bbs/test/read.cgi/support/1397047866/154`)
```
&#127988;&#917607;&#917602;&#917605;&#917614;&#917607;&#917631;
&#127988;&#917607;&#917602;&#917619;&#917603;&#917620;&#917631;
&#127988;&#917607;&#917602;&#917623;&#917612;&#917619;&#917631;
(以下省略)
```

[sub]: https://emojipedia.org/subdivision-flags/
[eng]: https://emojipedia.org/flag-england/

**Comment by mtasaka** [comment]
関係がありそうな気もしますが、 JDサポート掲示板で 155 156 157 はいずれも私の書き込みですが（IDは確かに全部同じですね）、jdimのスレ表示を見ると、157には鉛筆表示がついてますが、155 156には鉛筆表示がついてないです。だから、多分「自分が書き込んだ（と思っている）内容と、帰って来た内容が違う」（？）みたいな判定（？）をしているんだと思いますが...

**Comment by mtasaka** [comment]
上で、「自分が書き込んだ（と思っている）内容と、帰って来た内容が違う」（？）みたいな判定（？）をしているのかも、と書いた件は、結局

* スレに書き込む前に、「iconvにかける前の」レス（文章）を保存しておく
* スレに書き込む時、iconvにかけて、その後書き込む
* 書き込んだ後、スレを読み込む
* スレの中のレスと、保存しておいた文章が一致するものがあるかを調べ、あれば新たに鉛筆印をつける

という処理になっていたので、subdivision-flags があると、iconvに書けたときに一部の文字が欠落するので、保存しておいた文章と一致せず、鉛筆印がつかない、ということになってました。修正後は鉛筆印もつくようになってます。
