### ISSUE TITLE
unittestを試験的に導入する

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#45]
実装した機能をテストするためにunittestの試験導入を提案します。

**edit(2019-03-02):** コミットを更新
**edit(2019-03-03):** ダウンロードについてコメントを追加

### 動機
Unicode の数値文字参照(e.g. `&#1234;`, `&#x89ab;`)をコードポイントへデコードする処理に不具合があり文字化けする問題があります。
この不具合の修正には様々なパターンに対応するため分岐が複雑になっています。 https://github.com/ma8ma/JDim/commit/e673bf83ec51403cc2745b30e5ca6100a1eece82
そのため修正後の動作が正しいかどうか確認する方法が必要だと考えました。

#### テストパッケージの選択
現在のコミット https://github.com/ma8ma/JDim/commit/b92149a0051bcbddc8d5b1323966fd7d6985a03f では暫定的に [**Google Test**][gtest-page] (gtest)を利用しています。
gtest本体はリポジトリに同梱せずテストコードをビルドする際にダウンロード(git clone)する方法をとっています。テスト実行は開発者が手動で依存関係を追加しなくてすむようになっています。JDim本体のビルド(`make`, `make all`)ではテストパッケージのダウンロードは行われません。

また、JDim本体のビルドではテストコードをビルドしないようにmakeのプロセスを分離しました。
```sh
# JDim本体のビルド
autoreconf -i
./configure
make

# テストのセットアップ (googletest のダウンロード)
make -C test setup
# テストコードのビルドと実行
make test
```

#### 文書の変更
テストについては`test/README.md`に記載します。
`CONTRIBUTING.md`でテストケースの追加に言及しますがプルリクエストの条件にはしません。

#### 今のところはやらない
* 既存の機能にテストケースを付けるだけの修正
* プルリクエストのChecksを設定して継続的インテグレーション(CI)を行う

### ポイント
* テストパッケージはGoogle Testでいいか？
* テストパッケージの導入は別途インストール、同梱、ダウンロードのうちどれがよいか？

### 暫定的にGoogle Testを選択した理由
* 開発の活発さ
* webの情報量
* パッケージの大きさ (ダウンロードに耐えるか)
* 導入の容易さ (makeコマンドだけでセットアップから実行まで対応できる)
* テストケース追加の容易さ

[gtest-page]: https://github.com/google/googletest

**Comment by henrich** [comment]
> gtest本体はリポジトリに同梱せずテストコードをビルドする際にダウンロード(git clone)する方法をとっています。テスト実行は開発者が手動で依存関係を追加しなくてすむようになっています。

distro（Debian）的にはコケてくれた方が嬉しいです。理由はビルド時にはパッケージ以外の依存関係のダウンロードは禁止な為です。

**Comment by ma8ma** [comment]
@henrich https://github.com/ma8ma/JDim/commit/b92149a0051bcbddc8d5b1323966fd7d6985a03f では大丈夫だと思います。./configure後の`make` (または`make all`)の実行でgoogletestのダウンロードやテストは実行されません。明示的に`make -C test setup`を実行するとgoogletestのダウンロード、そして`make test`でテストコードのビルドと実行が行われます。

私の環境ではパッケージ管理システムからインストールしたgoogletestのソースパッケージを使ってテストコードのビルドと実行はできました。ソースからビルドしたライブラリ(`*.a`)やオブジェクトファイル(`*.o`)は`test/build`に生成されるので(out-of-sourceビルド)、`/usr/src`は汚れないはずです。
```sh
# Ubuntu 18.10の場合
# make -C test setup のかわりにaptでソースパッケージをインストールする
sudo apt install googletest
make test GTEST_DIR=/usr/src/googletest/googletest
```

個人的にはディストリのパッケージにあるgoogletestを別途インストールする方法は省力の点(ユーザーに要求するコマンド、makefileのルール実装)やgoogletestのバージョン互換性の問題でやや難しいと考えています。

**Comment by henrich** [comment]
@ma8ma 

> googletestのバージョン互換性の問題

これは（Debianに限って言えば）気にしなくてもいいです。理由はbackportパッケージを提供すれば済むので、unstableにある新しいバージョンだけ考えれば済む形になるので。

デフォルトではなくオプションでdistroのgoogletestパッケージを明示的に利用してダウンロードを抑制する、というのは同意できませんか？

**Comment by ma8ma** [comment]
@henrich
> デフォルトではなくオプションでdistroのgoogletestパッケージを明示的に利用してダウンロードを抑制する、というのは同意できませんか？

オプションでdistroパッケージを利用してダウンロードを抑制するは同意します。私の説明が微妙かもしれないのですみませんが確認させてください。

* JDim本体のビルドではgoogletestのダウンロードを絶対にしません。テストに興味がない場合はgoogletestと無縁です。
* テストプログラムのビルドではgoogletestのソースが必要になります。makeのサブコマンドを介したダウンロードは必須ではなくGTEST_DIRでソースディレクトリを指定することによって任意のものを使うことができます。

罫線以下の説明を要約しますとディストリパッケージを利用してテストする方法は
* `make -C test setup`の代わりに`sudo apt install googletest`でgoogletestをインストールする
* `make test`の代わりに`make test GTEST_DIR=/usr/src/googletest/googletest`でディストリのパッケージを利用してテストプログラムをビルドする

---

debian系の`googletest`パッケージはバイナリパッケージではなくソースパッケージのはずです(少なくともUbuntu 18.10では)。aptで`googletest`をインストールすると`/usr/src/googletest/`にソースコードが配置されるだけなので`gcc -lgoogletest`のようなコンパイラフラグやライブラリファイルの指定は利用できません。テストプログラムのビルドには`/usr/src/googletest/`にあるソースコードをコンパイルしてライブラリを生成してからリンクする必要があります。

私の案は make のサブコマンドを下の３つに分けます。
* jdim本体をビルドする`make` (他の２つに依存しない)
* googletestをgithubからダウンロードする`make -C test setup` (他の２つに依存しない)  
* テストコードとgoogletestをコンパイルしテストプログラムをビルドして実行する`make test` (jdim本体のビルドに依存する)

`make`や`make test`を実行しても`make -C test setup`はスキップされダウンロードは始まりません。つまり単に`make test`を実行してもテストプログラムのビルドは失敗します。

`make -C test setup`でgoogletestをダウンロードする代わりにディストリパッケージのgoogletestを利用するには`make test GTEST_DIR=/usr/src/googletest/googletest`でデフォルトのソースディレクトリを上書きして明示的に指定します。このソースディレクトリはgithubのgoogletestと同じレイアウトである必要があります(Ubuntu 18.10の`googletest`パッケージでは成功しました)。

ディストリの`googletest`パッケージをいつインストールするかはテスト実行者の責任です。jdimのconifgureスクリプトやmakefileルールはディストリの`googletest`パッケージをインストールする処理を行いません。また今のところ`make test GTEST_DIR=/path/to/googletest`以外で利用するソースを変更する方法やビルド済みのライブラリを指定する方法は未実装です。

長文すみません、自分用のメモです :cry:

**Comment by ma8ma** [comment]
googletestの導入機能を省略したPull Request(draft)を公開しました。#78
説明や手順など分かりやすい箇所がありましたらご指摘いただければ幸いです。
