### ISSUE TITLE
gcc11の警告: dynamic_castについて

### ISSUE THREAD

**Issue by mtasaka** [JDimproved/JDim#506]
gcc11の開発版でのbuildを試していますが、現段階で2つ警告が出ています

```
menubutton.cpp: In member function 'void SKELETON::MenuButton::append_menu(std::vector<std::__cxx11::basic_string<char> >&)':
menubutton.cpp:126:115: warning: 'this' pointer null [-Wnonnull]
  126 |             dynamic_cast< Gtk::Label* >( item->get_child() )->set_text( MISC::cut_str( items[ i ], MENU_MAX_LNG ) );
      |                                                                                                                   ^
In file included from /usr/include/gtkmm-3.0/gtkmm/accellabel.h:27,
                 from /usr/include/gtkmm-3.0/gtkmm/menuitem.h:32,
                 from /usr/include/gtkmm-3.0/gtkmm/menushell.h:30,
                 from /usr/include/gtkmm-3.0/gtkmm/menu.h:28,
                 from /usr/include/gtkmm-3.0/gtkmm/entry.h:29,
                 from /usr/include/gtkmm-3.0/gtkmm/treeview.h:41,
                 from /usr/include/gtkmm-3.0/gtkmm/combobox.h:33,
                 from /usr/include/gtkmm-3.0/gtkmm/appchooserbutton.h:27,
                 from /usr/include/gtkmm-3.0/gtkmm.h:107,
                 from menubutton.h:8,
                 from menubutton.cpp:7:
/usr/include/gtkmm-3.0/gtkmm/label.h:161:8: note: in a call to non-static member function 'void Gtk::Label::set_text(const Glib::ustring&)'
  161 |   void set_text(const Glib::ustring & str);
      |        ^~~~~~~~

============================================================

drawareabase.cpp: In static member function 'static gboolean ARTICLE::DrawAreaBase::deceleration_tick_cb(GtkWidget*, GdkFrameClock*, gpointer)':
drawareabase.cpp:5405:83: warning: 'this' pointer null [-Wnonnull]
 5405 |     return dynamic_cast< DrawAreaBase* >( widget )->deceleration_tick_impl( clock );
      |                                                                                   ^
In file included from drawareabase.cpp:13:
drawareabase.h:503:18: note: in a call to non-static member function 'gboolean ARTICLE::DrawAreaBase::deceleration_tick_impl(GdkFrameClock*)'
  503 |         gboolean deceleration_tick_impl( GdkFrameClock* clock );
      |                  ^~~~~~~~~~~~~~~~~~~~~~
```
まだ開発中だからか、警告の英語の内容が文法的になってないので分りづらいですが、
```
 (dynamic_cast< Gtk::Label* >( item->get_child() ) ? : (abort(), nullptr))->set_text( MISC::cut_str( items[ i ], MENU_MAX_LNG ) );
```
とかに変更すると、（GNU拡張を使っていることでの警告が出るものの）`-Wnonnull` の警告はでなくなるので、おそらく「`dynamic_cast` をするとnullptrが返る可能性があり、その場合メンバー関数にアクセスするとき、`this` はnonnull でなければならないので、未定義動作になる」という意味だと思います。  

要は「`dynamic_cast`するなら null-check する必要がある」ということだと思いますが、結構面倒くさそうですよね...

**Comment by ma8ma** [comment]
nonnullの警告は先にデリファレンスしてから参照へdynamic_castすれば回避できるかもしれません。(ただし絶対にnullにならない場所限定)

`menubutton.cpp`のほうはGtk::Labelの生成が明示的でないのでnullチェック追加のほうが無難だと思います。
https://github.com/JDimproved/JDim/blob/3535ce72951ece762330573ca0754230eceecb7e/src/skeleton/menubutton.cpp#L117-L130

`drawareabase.cpp`のほうはコールバック関数の引数由来なのでコンパイラが許してくれれば参照のキャストに変更しても大丈夫と考えてます。他の方法として[c++ API][api]を見つけましたがgtkmm 3.24以上が必要そうです。条件コンパイルを増やすのはちょっと気が進まないので3.22(ubuntu 18.04)をサポートしている間は使いにくいです。
https://github.com/JDimproved/JDim/blob/3535ce72951ece762330573ca0754230eceecb7e/src/article/drawareabase.cpp#L5402-L5406


[mb]: https://github.com/JDimproved/JDim/blob/3535ce72951ece762330573ca0754230eceecb7e/src/skeleton/menubutton.cpp#L126
[db]: https://github.com/JDimproved/JDim/blob/3535ce72951ece762330573ca0754230eceecb7e/src/article/drawareabase.cpp#L5405
[api]: https://developer.gnome.org/gtkmm/stable/classGtk_1_1Widget.html#a0087dc87b7dfa41988affa55d3fbf834

**Comment by mtasaka** [comment]
JDim 0.5.0 が出る前に消したいですが... (Fedora rawhide がもう本格的に gcc11開発版になって、警告が出続けるので...）

`drawareabase.cpp` の方は、gtkmm (>= 3.24)のwrapperの方は、本質的に`dynamic_cast` でなく `static_cast` しているのと変わらないですね...まあこれでもいいかも知れませんが
https://gitlab.gnome.org/GNOME/gtkmm/-/blob/a99220925b22a02d58e02fb1c5020d0c1d3ba389/gtk/src/widget.ccg#L113

`menubutton.cpp` の方は null check を入れるのが無難ですかね。

**Comment by ma8ma** [comment]
修正は両方ともnull check追加でよいと思います。こちらでテストしたらプルリク出しますがパッチの用意があればマージします。

gtkmm関数オブジェクトをvoid*にキャストというのは盲点だった :fearful:

**Comment by mtasaka** [comment]
今のところまだパッチは用意してません... もし修正して下されば確認します

**Comment by ma8ma** [comment]
@mtasaka 
#506 を書いてみました。よろしくお願いします。
