### ISSUE TITLE
正規表現ライブラリPOSIX regexのサポートを廃止する

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#521]
正規表現ライブラリのPOSIX regex(`--with-regex=posix`)のサポートを廃止してビルドオプションから取り除くことを提案します。

### 動機
ビルドオプションを減らし動作確認にかかる時間を削減します。

POSIX regexは幅広い環境で利用できる利点がありますが、PCRE系の正規表現と比べると機能が少ないです。
そのためposixでも機能するように正規表現を設定しなければならずメンテナンスの手間が増えます。

デフォルトオプションのGRegex(`--with-regex=glib`)はGlibに付属しているのでJDimがビルド可能な環境なら利用できます。(Glib 2.32で[GRegexを無効するオプションは削除されました][glib2-32])
また、[glibがデフォルト][451]になった後掲示板スレッドの動作報告では正規表現にposixを指定している利用者はいませんでした。

### 作業の進捗
updated: 2021-01-16
#### 廃止前のステップ (~v0.5.0)
- [x] \(#528) 廃止予定になったことをドキュメントに書き、ビルド時にposixオプションを指定すると警告表示する
#### 廃止後のステップ part1 (~v0.6.0)
- [x] \(#568) ビルドオプションにposixを指定するとエラーになるよう変更する
- [x] \(#568) ソースコードを整理する
#### 廃止後のステップ part2 (~v0.7.0)
- [ ] \(#778) posixオプションを完全に削除する

[451]: https://github.com/JDimproved/JDim/pull/451
[glib2-32]: https://gitlab.gnome.org/GNOME/glib/-/commit/d70634526d43a9d9281301c2097c788ca575e318

**Comment by a-long-time-beginner** [comment]
その行程で異論はないです

**Comment by ma8ma** [comment]
POSIX regexのサポート廃止で進めていきます。

**Comment by ma8ma** [comment]
configureオプション`--with-regex=posix`を廃止しました。(#568)
