### ISSUE TITLE
長大なスレッド(>11000レス?)を開くと落ちる不具合を修正する

### ISSUE THREAD

**Issue by taro-yamada** [JDimproved/JDim#53]
[edit] タイトルを変更しました。

現在[長大なスレッド(>11000レス?)を開くと落ちる不具合を修正する](https://github.com/JDimproved/JDim/projects/1#card-18008854)に挑戦しています。

ですがレス数が増える(25000とか)に従ってNodeTreeBase::check_id_name()が許容できないレベルで時間を食うようになります。
(私の環境でhttp://matsuri.5ch.net/test/read.cgi/anime2/1499345272/ を開こうとするとポップアップ及びスレを開くのにそれぞれ30秒程度、そのうち95%近くをNodeTreeBase::check_id_name()が消費)

原因を調べてみると、NodeTreeBase::update_id_name()がfrom_number(例. 1)からto_number(例. 25000)まで繰り返しを回す中でcheck_id_name()が呼ばれるのですが、さらにその中でnumber(例. 25000)から1まで同じIDが見つかるまで逆順に辿ることが繰り返されているため25000回のループの中で更に25000回(最大)ループするといったような状態となっているためのようです。

また、update_id_name()という名前に反してそれ自身はcheck_id_name()を呼ぶだけ、check_id_name()はその名前に反してアップデートを行っている、という状態にもなっています。

そこでcheck_id_name()はupdate_id_name()内でしか使用されていないのでそれを削除し、update_id_name()内でIDと発言数、レス番号をまとめた一覧を用意、1回目のループでそれを更新しその後もう一回のループでその一覧を元に各NODEを更新するという形にするとレス数が増加しても問題ないレスポンス速度になりそうです。
taro-yamada/JDim@41306cfb373f25dae1e3369a93f0d4b11508962d

もし削除するなら一貫性の点からはfontidやreferenceも削除すべきかと思いますが、いま直接は必要ない部分を変更して新たな問題が起きてしまっても良くないと思うので//TODOコメントだけ付け加えようと思っています。

如何でしょうか。

**Comment by ma8ma** [comment]
修正を試して11000レスの上限解除と読み込みが速くなったのを確認しました。:+1: #46 で挙げられている8000-9000レスあるスレッドの読み込みも良くなってますね。

ただどうも特定のレスへの移動が動かなくなったようです。
スレを開くと以前読んだレスの位置に合わせる、キーボードによる移動：前後のレス(n,p)、書き込んだレス(shift+F2)、新着レス(F4)、レス番号指定などが動いてません…
スクロールバーのドラッグ、キーボードによる中速高速の上下移動(page up/down)、マウスホイールによるスクロールは動作します。

**Comment by taro-yamada** [comment]
ありがとうございます、こちらでも確認しました。

LayoutTree::get_header_of_resを呼び出している側でnullかどうかのチェックをしているのでそもそも当該部分の要素の確認は要らなかったかも知れません。

ほかにもまだまだ色々不適切、検討不足な感じなのでもう少し色々考えてみますが、方向性としてはアリかな、ということのようで安心しました。

**Comment by ma8ma** [comment]
上のedit2はレス番号は関係なく11000以上あるスレのどこでもいいのでしおりを設定すると異常な状態になるようです。しおりを設定してjdimを終了しキャッシュディレクトリ内の1499345272.infoファイルを見るとbookmarkの項目が`bookmark = 1 11000 11001 11002 ... 27000 ...`となっています。
9000レスのスレッドではしおりの設定解除が正常に動作するのを確認しました。

**Comment by taro-yamada** [comment]
しおりはNODETREE等の要素数が最大MAX_RESNUMBERな事を前提としているところにvector化でそれ以上の要素を入れられるようにしてしまっていたことが原因なようでした。

なので要素を挿入する前にMAX_RESNUMBER以下であることを確認するようにして対応しようと思います。
(ただそうするとvector/unordered_map化する意味も半減なのでそちらは一旦置いておきます)


影響範囲が大きいので目処が付いたら5chのスレでもテストをお願いしてみようと思います！
色々確認していただいてありがとうございました。
(というかこちらの圧倒的な確認不足な状態で申し訳ありませんでした :sweat:

**Comment by ma8ma** [comment]
@taro-yamada 正直に言うと腰が重い課題だったのでこちらこそ提案ありがとうございます。

しおりなどレスの情報は`std::vector<char>`にレス番号をindexとしてboolのフラグで管理しているようなので、レス番号をキーにした`std:set<int>`や`std::unordered_set<int>`で管理できるかもと予想しています。順序やvectorのサイズに依存したコードがたくさんあった場合は厳しいと思いますが…こちらでもちょっと実験してみます。

**Comment by taro-yamada** [comment]
@ma8ma
v2をpushしました。

しおり等の問題は各ノードヘッダの作成時点でMAX_RESNUMBER以下に制限することでm_number_loadが適切に設定されるのでとりあえず大丈夫っぽい？感じです(自信なし…)

ひとまずPR出す前に一旦5chのスレでもテストをお願いしてみようと思います。

**Comment by ma8ma** [comment]
@taro-yamada レス数上限を引き上げた修正をアップしました (ma8ma#30)
この変更では初期化で11000レス分のメモリを確保、スレが伸びると自動的に1048576レス(2の20乗)まで拡張されます。現存する27000レスを超えるスレだとどうなるか試してないですが100万レスは実用に耐えないと思います。

**Comment by ma8ma** [comment]
@taro-yamada v2 設定の変更と27000レス表示を確認しました。
気づいた点ですが5桁のアンカーがリンクしていないのと[レス番号にshort使っている箇所][res-short]があります(レス番号はJD時代からそのままです)。

[taro-yamada v2][compare-v2] と ma8ma#30 の比較です。

| | taro-yamada v2 | ma8ma#30
| --- | --- | ---
| 最大表示可能レス数 | `INT_MAX`(2147483647) | 固定(1048576)
| 最大表示可能レス数の変更方法 | `about:config` | 無し
| デフォルトの表示可能レス数 | 11000 | 11000レス分のメモリを確保する
| メモリ確保 | 固定(設定のレス数) | 動的に拡張(配列の容量を超えたら再確保)
| 最大表示可能レス数を超えた場合 | それ以上表示されない | クラッシュ (-> 表示を止めるべきか)

[res-short]: https://github.com/JDimproved/JDim/blob/e649cc2f0c07d510b939285e5a39b45d40c28c8e/src/dbtree/node.h#L116
[compare-v2]: https://github.com/JDimproved/JDim/compare/master...taro-yamada:90619ae

**Comment by taro-yamada** [comment]
@ma8ma 
確かにしおり等はレス数より圧倒的に少ないだろうし
レス数もほとんどのスレでは1000以下なので常にMAX_RESNUMBER個分実際に確保するのは無駄が多すぎですね
(v2では｢push_back()とかat()って遅いって言うしなー｣とよく考えずに変更してしまいました…)


となるとv2をベースに要素の確保周りをv1に戻し、更に ma8ma/JDim@4e27a7f95ad847e192a6de587be8936d03d6bd66 をcherry-pickする感じでしょうか



不慣れなもので安易にv1をなかった事に変更してv2をforce pushしてしまったり、色々面倒をおかけしてすいません。

**Comment by ma8ma** [comment]
@taro-yamada 
> となるとv2をベースに要素の確保周りをv1に戻し、更に [ma8ma/JDim@4e27a7f](https://github.com/ma8ma/JDim/commit/4e27a7f95ad847e192a6de587be8936d03d6bd66) と [ma8ma/JDim@71996ed](https://github.com/ma8ma/JDim/commit/71996ed62f2e0dcc038acc88f4080f4c4dac28c7) の一部をcherry-pickする感じでしょうか

私は設定面倒くさい人なのでまず到達が考えられない長さ(100万)まで勝手にレスを表示するようになっていれば楽だなと考えています。:sweat_smile:
ただ、修正しても5万、10万、それ以上のレスを表示するとパフォーマンスがかなり落ちると予想しますので最大表示可能レス数を設定できるのはいいアイデアだと思います。:+1:

> あと、｢sizeof(int) >= 4を保証するためuniform initializationを使う｣というのがちょっと意図というか意味がよく理解できないのですが、どういうことか教えていただけますでしょうか
> (不勉強ですいません、sizeof(int) >= 4を保証することとuniform initializationを使うことの間にどういう関係あるのかわからない…)

`sizeof(int) == 2`となる環境(16bit OS?)では[`src/global.h`の`int kMaxResNumber{ 1048576 };`][global-h]はコンパイルできません。gcc だと下のようなエラーが出ます(エラーだすためにint16_tを使ってます)。
```
$ g++ -std=c++11 test.cc 
test.cc: In function ‘int main()’:
test.cc:12:24: error: narrowing conversion of ‘1048576’ from ‘int’ to ‘int16_t’ {aka ‘short int’} inside { } [-Wnarrowing]
     int16_t x{ 1048576 };
```
これによってコンパイルできなくなる16bit環境が今も存在するか分かりませんが整数オーバーフローによる問題を回避するためのハードルとして書きました。

> 色々不慣れなもので安易にv1をなかった事に変更してv2をforce pushしてしまったり、面倒をおかけしてすいません。

いえいえ、こちらもはやく反応できなくてすみません。一定の修正を残す場合はマージしないPRを作って閉じておけばそのままPRにリンクが残るので参照しやすいかなと思います。

[global-h]: https://github.com/ma8ma/JDim/blob/71996ed62f2e0dcc038acc88f4080f4c4dac28c7/src/global.h#L22

**Comment by taro-yamada** [comment]
> sizeof(int) == 2となる環境(16bit OS?)ではsrc/global.hのint kMaxResNumber{ 1048576 };はコンパイルできません。gcc だと下のようなエラーが出ます(エラーだすためにint16_tを使ってます)。

なるほど、わかりやすい説明ありがとうございます！

私も設定煩わしい派なので、デフォルトの上限を10万で少なくしたい人は設定変更、また上限としての最大表示可能数が板ごとにあると逆にややこしい&煩わしい気がするので全体設定のみという方向でやってみます！:thumbsup:

**Comment by ma8ma** [comment]
@taro-yamada 
masterブランチに対する差分が大きくなりそうなので https://github.com/ma8ma/JDim/pull/30/commits/8c5cd0512ebe25f9ea0d7b99aa5051e9a56533b8 (レス情報を`std::unordered_set<int>`化) と https://github.com/ma8ma/JDim/pull/30/commits/47960fe66439f6095ba7da5a7ab85877a84d6696 (変数名の変更)の一部を先行してPR提出するか考えてます。しおりや書き込みなどレス情報の取扱いは現状のパッチのままで問題ないでしょうか？

**Comment by taro-yamada** [comment]
@ma8ma 
了解です、宜しくおねがいします。
(ma8ma@a03762885dd9fdce5c4c8ad20d738ed4a1abf256 、 ma8ma@c81d69c09da766fbfd0dd8be39db458ce0f6d82e は含まないということで良いんですよね？)


あるいはこちらもそろそろPRを送ろうかと思っていたのでこちらでやらせていただいても、ma8maさんにとって楽な方でお願いします:thumbsup:

**Comment by ma8ma** [comment]
PR #59 を提出しました。

> ([ma8ma/JDim@a037628](https://github.com/ma8ma/JDim/commit/a03762885dd9fdce5c4c8ad20d738ed4a1abf256) 、 [ma8ma/JDim@c81d69c](https://github.com/ma8ma/JDim/commit/c81d69c09da766fbfd0dd8be39db458ce0f6d82e) は含まないということで良いんですよね？)

そちらは @taro-yamada さんが書いたパッチであるのと最大表示可能レス数に直接関係していることからPRに含めないようにしました。

**Comment by ma8ma** [comment]
@taro-yamada 
fix_large_resnumber に気がついた点をコメントしました。
https://github.com/taro-yamada/JDim/commit/7aacc002ace44a810cdf61caa3eca447c0cbc770#r32858920
https://github.com/taro-yamada/JDim/commit/fafa0e1aaa88e2e12e0ce48f07adfb8387c33fc0#r32858980
https://github.com/taro-yamada/JDim/commit/e368f796bcd79a44b3ef5d4567d31e62a5623688#r32859019
https://github.com/taro-yamada/JDim/commit/4c4ba43428511b3e582a9262220dc62a5428f82f#r32859051

**Comment by taro-yamada** [comment]
マージしていただいたのでこちらはcloseします、ありがとうございました！
