### ISSUE TITLE
オンラインマニュアルの作成

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#66]
現在、JDimは本家JDのオンラインマニュアルを[参照][jd-manual]しています。
今のところJDimと本家の差は小さいですが、機能の追加や削除を積み重ねていくと本家のマニュアルと異なる部分が増えてくることが予想されます。そのためJDimのほうでオンラインマニュアルを作成・保守したほうがよいと考えています。

具体的な方法についてですが、本家のマニュアルをそのまま引き継ぐのではなく軽量マークアップ言語markdownを使って移植するのはどうでしょうか。

##### markdownを使う案
* markdownファイルをJDimへコミットし[GitHub Pages][gh-pages] ([jekyll][jekyll])を設定して公開する
  -  masterブランチの/docsディレクトリ
  - またはgh-pagesブランチ (`git checkout --orphan gh-pages`で独立させる)
* またはリポジトリのwikiをオンラインマニュアルとして使う
* もしくはマニュアル用リポジトリを作りJDim本体とは別に管理する

markdown利用の理由はツールの用意や編集参加のハードルを下げるためです。GitHubではコメント機能などmarkdownを使う機会があるためマニュアルのファイル形式に採用すればよりコントリビュートしやくなると思います。加えて、本家マニュアルはxmlで書かれていてhtmlへ変換するときにjava製ツールを使うので編集しようと思ってもとっつきにくい感じがします。

[jd-manual]: https://jd4linux.osdn.jp/manual/289/
[gh-pages]: https://help.github.com/en/articles/configuring-a-publishing-source-for-github-pages
[jekyll]: https://jekyllrb.com/

---

#### マニュアルを置く場所の比較
edit: gh-pagesブランチについて記載

| 場所 | 特徴
| --- | ---
| masterブランチの/docs | JDim本体と同じブランチにファイルがあるとまとめて修正しやすい
| gh-pagesブランチ | ブランチを分けるとファイル管理しやすい
| wiki | オンライン編集が容易、ユーザーが編集できるよう設定できる
| マニュアル用リポジトリ | メンテナンス担当がいるなら編集作業がしやすいかもしれない

**Comment by yama-natuki** [comment]
wikiとどっちがいいのか迷いますが、Markdownでdocsディレクトリに、でいいかなと思います。
JDのwikiと同じように各ディストリごとの導入手順が充実していけばいいなと思いますが、こればかりはユーザーからのアクションを期待したいところですね。

**Comment by ma8ma** [comment]
マニュアルを公開しましたのでissueを閉じます。 (https://jdimproved.github.io/JDim/)
