### ISSUE TITLE
[Question][Android]配信スレ詳細画面のOFF AIR時の背景につきまして

### ISSUE THREAD

**Issue by sft-tester** [JDimproved/JDim#67]
## 現象
参照資料「生配信_2019_1Q」>31ページより、
配信スレ詳細画面のOFF AIR時の背景は「Off-Air」となっておりますが、
実機とZeplinの画像では、
「ON AIR」がグレーアウトした状態の背景が表示されております。

こちら、OFF AIR時は上記のどちらの表示が正となりますでしょうか。
お手数をおかけいたしますが、ご確認の程よろしくお願いいたします。

##参照資料
「生配信_2019_1Q」>31ページ
https://docs.google.com/presentation/d/1JhtwA-40rrWorpXJkAOH_udXdgrZdCoTnyspwGwjvP4/edit#slide=id.g489eb8071b_2_10

Zeplin>Android / BC / 配信者 / 配信スレ / 非配信中
https://app.zeplin.io/project/5b750ec9bb5349735048bf6a/screen/5c3d574a79209a523e1eccdb

## 手順
1.任意の配信スレッドを作成する
2.配信スレッド詳細画面に遷移する
3.OFF AIR時の背景画像を確認する
4.現象発生

## 確認環境・再現性
SO-02H(6.0)...3/3

## テスト対象
`16.0.0` /dev05

![Question Android 配信スレ詳細画面のOFF AIR時の背景につきまして](https://user-images.githubusercontent.com/10523978/55371248-7e7a8900-5538-11e9-9633-5b1720b55e58.jpg)

**Comment by sft-tester** [comment]
大変申し訳ございません。
起票先を誤ってしまいました。
こちらはクローズとさせていただきます。

**Comment by sft-tester** [comment]
@ma8ma さん
大変申し訳ございません
こちら起票先を誤ってしまいましたので、issueの削除をお願い致します。

**Comment by ma8ma** [comment]
@yama-natuki issueを削除するため https://github.com/organizations/JDimproved/settings/member_privileges の _Issue deletion (Beta)_ を有効にします。
