### ISSUE TITLE
gtkmm 2.18未満のサポートを終了予定にする

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#71]
バージョン2.18未満のgtkmmについてサポート終了予定にすることを提案します。

#### バージョン2.18の理由
バージョン2.18は2020年までサポートされるRHEL/CentOS 6に入っています([リスト][list])。 同じ時期かこれより古い時期にリリースされた(有償サポートを除いた)ディストリビューションはEOLや開発終了に達していて考慮しなくていいと思います。

#### なぜサポート終了するのか
使われていないコードを削除して保守性を高めるためです。2018〜2019年の5chスレッドで動作環境のコピペを探してもgtkmm 2.24未満の環境のレポートがないことが根拠の一つです。

#### サポート終了までの手順案

1. READMEやINSTALLのドキュメントで2.18未満のサポート終了予定を表示する
2. 次のリリース、または次々回のリリース後にconfigureの要求バージョンを`gtkmm-2.4 >= 2.18.0`へ引き上げドキュメントを更新する
3. 2.から少し時間を置いて古いバージョンのソースコードを削除する

[list]: https://rpmfind.net/linux/rpm2html/search.php?query=pkgconfig(gtkmm-2.4)

**Comment by yama-natuki** [comment]
いいと思います。賛成です。

**Comment by ma8ma** [comment]
他の作業の進捗を見ながら進めたいと思います。
