### ISSUE TITLE
Debian stretchのサポートを終了する

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#777]
### 背景や動機

[RFC 0006][rfc0006]に基づき次期リリースをもってDebian stretch(2017年リリース)のサポートを終了し動作環境を更新することを提案します。

[rfc0006]: https://github.com/JDimproved/rfcs/blob/master/docs/0006-platform-support.md

#### 動作環境の更新案
Ubuntu 18.04(2018年リリース)を参考にツールチェーンとライブラリの要件を更新します。

- [glibmm 2.56.0](https://launchpad.net/ubuntu/+source/glibmm2.4) 以上
- [gnutls 3.5.18](https://launchpad.net/ubuntu/+source/gnutls28) 以上
- [openssl 1.1.0](https://launchpad.net/ubuntu/+source/openssl) 以上
- [g++ 7][gcc7] 以上、または [clang++ 6.0][clang6] 以上

[gcc7]: https://launchpad.net/ubuntu/+source/gcc-7
[clang6]: https://launchpad.net/ubuntu/+source/llvm-toolchain-6.0

また、古い環境での検証が困難なため推奨環境も更新します。

- [Linux Kernel 4.4.0](https://launchpad.net/ubuntu/+source/linux) 以上

#### 動作環境の更新時期
2022-01

詳細日程はv0.7.0のリリースが計画されてから決定します。

#### 作業の進捗

- [x] \(#781) ドキュメントを更新して動作環境の更新予定を知らせる
- [x] v0.7.0リリース後にライブラリの要件を変更する

その後は新しい機能を使ってコードや機能を修正していきます。

### 代替案

なし

### 追加の情報

なし

**Comment by henrich** [comment]
LGTM, oldoldstableは正直考えたくないのでぜひ進めてください。

**Comment by ma8ma** [comment]
動作環境の更新を進めていきたいと思います。

**Comment by ma8ma** [comment]
動作環境を更新したため閉じます。 #898
