### ISSUE TITLE
./configure CPU別の最適化オプションを廃止予定にする

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#80]
configureスクリプトのCPU別の最適化オプションを廃止予定にすることを提案します。

#### 理由
- オプションになっているCPUは古い世代であり最近の世代に対応していない。
- 最適化に関心のあるユーザーなら自分のマシンのCPUとgcc/clangのコンパイラオプションを調べてフラグを指定するのは難しくないはず。
  ```
  ./configure CXXFLAGS="-march=core2"
  ```

#### 廃止の手順案
1. configureスクリプトやドキュメントを修正してオプションが廃止予定になったことを通知する。
   代替手段としてCXXFLAGSで最適化オプションを指定する方法を示す。
2. 次期バージョンのリリース後にオプションを削除する。

#### 廃止予定にするconfigureオプション
`--with-native`はどのCPUでも有効なためこの提案では廃止しない。(別の理由/提案で廃止予定になる可能性はある)

- `--with-core2duo`
- `--with-athlon64`
- `--with-atom`
- `--with-ppc7400`
- `--with-ppc7450`

**Comment by yama-natuki** [comment]
賛成です:)

**Comment by yama-natuki** [comment]
>>代替手段としてCXXFLAGSで最適化オプションを指定する方法を示す。
これはTipsにでも？

**Comment by ma8ma** [comment]
@yama-natuki INSTALLファイルに記載を考えていましたが、Tipsも賛成です :+1:

- configureスクリプトで`--with-core2duo`などのオプションを指定したときに警告する。
- README.mdのTipsに項目(CPU指定で最適化する)を追加する。
  マシンのCPUを調べる方法もあれば役に立つかも。
- INSTALLのconfigureオプションにオプションの廃止予定とCXXFLAGSによる代替方法を記載する。
