### ISSUE TITLE
衝突するconfigureオプションをグループ化する

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#81]
衝突する（どれか一つしか指定できない）configureオプションをグループ化することを提案します。
グループ化は`--with-foo=[baz|qux]`のように指定のオプション値(`baz`か`qux`)を選択させます。

#### 長所と短所
- :+1: 衝突関係がはっきりする
- :+1: オプションの数が減り分かりやすくなる
- :-1: オプション値を指定するときにシェル補完を当てにできない
- :-1: オプション値ごとにヘルプメッセージが表示できない

#### グループ化の手順案
新オプションの導入と旧オプションの廃止予定を進めます。

1. グループ化された新オプションをconfigureスクリプトに実装する。
2. configureスクリプトやドキュメントを修正して旧オプションが廃止予定になったことを通知する。代替手段として新オプションを指定する方法を示す。
3. 次期バージョンのリリース後に旧オプションを削除する。

#### グループ化するconfigureオプション案
| 現状 | 新オプション | 指定しない場合(デフォルト) |
| -- | -- | -- |
| `--with-gthread`<br>`--with-stdthread` | `--with-thread=[posix\|glib\|std]` | `posix` |
| `--with-oniguruma`<br>`--with-pcre` | `--with-regex=[posix\|oniguruma\|pcre]` | `posix` |
| `--with-openssl` | `--with-tls=[gnutls\|openssl]` | `gnutls` |

##### エラーとする値
グループに入ってない値(e.g. `--with-thread=foobar`)や値なしオプション(e.g. `--with-thread`)はエラーとします。

**Comment by yama-natuki** [comment]
いいと思います。
