### ISSUE TITLE
メンテナの交代について

### ISSUE THREAD

**Issue by yama-natuki** [JDimproved/JDim#86]
最近忙しく、土日出勤などでまとまった時間も取れないため、JDimの管理を降りたいと思います。
＠ma8ma  さんには負担を掛けることになり心苦しくもありますが、JDを次代に繋げるためとホスティングしてきた事が意味はあったのかなと少し嬉しく思います。

**Comment by ma8ma** [comment]
@yama-natuki メンテナ交代の件かしこまりました。
GTK3サポートをはじめ様々な提案を @yama-natuki さんに後押していただき心から感謝しております。
これまでJD/JDimのメンテナンスをしてくださり誠にありがとうございます。
