### ISSUE TITLE
将来のリリースでAutotools(./configure)のサポートを終了してMesonに移行する

### ISSUE THREAD

**Issue by ma8ma** [JDimproved/JDim#897]
**edit(2022-11-05)**: Autotoolsのサポートは2023年7月のリリースをもって終了します。

---
将来のリリースでAutotools(./configure)のサポートを終了してMesonに移行する

### 背景や動機

JD/JDimをビルドするツールとしてAutotoolsが使われてきましたがスクリプトのメンテナンスに難しい点があります。

- スクリプトファイルは[autoconf]、[automake]を中心にmakeやシェルスクリプトなどが混ざっている
- シェルスクリプトに近い構文であり数値、文字列、配列の区別がゆるい
- ファイルの書き方を間違えたときエラーが分かりにくい・エラーとならない場合がある

2022年現在、Autotoolsの代替ツールとしてJDimにMesonのサポートを追加しています。
[Meson]はAutotoolsの難しいところを変更してあります。

- 構成ファイルは主に一種類[^1]でCLIツールや別のスクリプトを使う箇所が少なくなっている
- スクリプト言語に似た構文で数値、文字列、配列などが明確に分かれており型が合わない操作はエラーになる
- Autotoolsと比べるとファイルの書き方を間違えたとき表示されるエラーが分かりやすい

JDimはC++言語を利用しているのでC++を使う貢献者には馴染みやすい見た目と思います。

[^1]: クロスコンパイルで追加の設定ファイルが必要

#### 移行しても解決しないポイント
- 内容（オプション、依存関係、ビルドターゲットなど）はAutotoolsと変わらない
- 一つのファイル形式にはまとまらないため追加のスクリプトが必要な箇所がある
- 固有の環境でしか動かない書き方など落とし穴はある

[autoconf]: https://www.gnu.org/software/autoconf/
[automake]: https://www.gnu.org/software/automake/automake.html
[Meson]: https://mesonbuild.com/

#### Mesonの動作環境
Mesonを動かすにはpython3と[ninja]が必要になります。
Debian、Ubuntu、FreeBSDでMesonを利用したJDimのビルドを確認していますが
JDimを利用できるプラットフォームがMesonにもれなく対応しているかは不明です。

JDimのMeson構成ファイルはバージョン0.49が必要でサポート中の[Ubuntu 18.04]をカバーしていません。
[Debian buster]からディストロに入っているMesonを利用できるようになります。

[ninja]: https://ninja-build.org/

#### ディストロのパッケージング
Mesonの言及がありパッケージングに使えるようですがJDimに適用できるか未検証です。
- Arch Linux: https://wiki.archlinux.org/title/Meson_package_guidelines
- Debian: https://manpages.debian.org/testing/debhelper/debhelper.7.en.html
- Fedora: https://docs.fedoraproject.org/en-US/packaging-guidelines/Meson/

[Ubuntu 18.04]: https://launchpad.net/ubuntu/+source/meson
[Debian buster]: https://packages.debian.org/source/oldstable/meson

### 解決方法

ディストロのパッケージングに差し支えなければAutotoolsのサポートを廃止してMesonに移行したいと考えています。

### 代替案

- **Autotoolsのサポートを続ける**

- **Autotoolsを廃止予定にするが削除せず残しておく**
  新しいアップデートはMesonのみ追加します。

- **他のビルドツール(CMakeなど)を利用する**  
  cmakeのテスト: ma8ma/JDim#61

### 追加の情報

意見やアイデアなどコメントしていただけると幸いです。

CC: @henrich @mtasaka @naniwaKun

**Comment by mtasaka** [comment]
Fedora ではnightly build (nightly-2 branch) では meson に対応したので、大丈夫です。次のバージョンがリリースされたら、本ビルドでもmesonに移行します。
sanitizer buildとかに対応する為、色々spec fileが複雑になってますが、参考にしてください。

https://src.fedoraproject.org/rpms/jd/blob/b2d927b8daced575e4c8619f1b2dd85772b46f70/f/jd.spec

**Comment by ma8ma** [comment]
@mtasaka
更新ありがとうございます。
AddressSanitizerの件は対応を検討するためissueを開きたいと思います。

**Comment by ma8ma** [comment]
Autotoolsのサポート終了の手続きを定めるRFCを提出しました。 JDimproved/rfcs#8
10月頃までコメント募集期間にしたいと思います。

**Comment by ma8ma** [comment]
[0012-end-of-autotools-support.md](https://github.com/JDimproved/rfcs/blob/master/docs/0012-end-of-autotools-support.md)

RFCをマージしました。Autotoolsサポート終了の作業を進めていきます。

**Comment by ma8ma** [comment]
#### mesonの代替実装 [muon] について
https://github.com/JDimproved/JDim/commit/67596c69046cb4fe0ddca89a6d4cf5d3103e6c46 の修正でmuonを使ったビルドが可能になりました。
muonをサポートをする基準や目標などは特に計画していませんが今後の開発・メンテナンスの状況に応じて考えたいと思います。

[muon]: https://sr.ht/~lattis/muon/

**Comment by ma8ma** [comment]
Autotoolsのサポートを終了してmasterブランチから関連のスクリプトファイルを削除しましたので閉じます。
