### ISSUE TITLE
Debian10にてタブ一覧表示がスクロール出来ない

### ISSUE THREAD

**Issue by orenomask** [JDimproved/JDim#985]
**バグの説明**
複数のタブを開いていて、多くなると右上のタブ一覧表示がスクロール出来ない
Debian busterのリポジトリにあるJDim 0.1.0-20190122では、開いてる全部のタブ一覧表示が出来ていた
(https://next2ch.net/test/read.cgi/linux/1613035222/900)

**再現の方法**
Debian10環境にてスレビュー等のタブを多数開いた状態で「タブの一覧表示」ボタンをクリック

**やりたかったこと・期待する結果**
「タブの一覧表示」ボタンクリック→直下スクリーンショットの様に一覧多数の場合スクロールできる
![通常スクショ](https://i.imgur.com/5tqPdgI.jpg)

**スクリーンショット(不具合の再現)**
![バグスクショ](https://i.imgur.com/QnB2VBl.jpg)

**動作環境**
[バージョン] JDim 0.7.0-20220522(git:24aedf0d7a)
[ディストリ ] Debian GNU/Linux 10 (buster) (x86_64)
[パッケージ] バイナリ/ソース( <配布元> )
[ DE／WM ] MATE
[　gtkmm 　] 3.24.0
[　glibmm 　] 2.58.0
[　TLS lib　] GnuTLS 3.6.7
[オプション ] '--with-native''--with-pangolayout'
[ そ の 他 ]
(https://next2ch.net/test/read.cgi/linux/1613035222/900)

**追加の情報**
・ビルドオプション無しでも変化なし(https://next2ch.net/test/read.cgi/linux/1613035222/903)
・DEはMATEだが他のDEでも再現可能かも知れない
・Ubuntu 20.04LTS・FreeBSD 13.1-RELEASEでは再現しない模様
　(https://next2ch.net/test/read.cgi/linux/1613035222/901-902n)

**Comment by ma8ma** [comment]
週末までに確認するための環境を用意できるかわからないので
GTK v3.24.6未満の環境では`gtk_menu_popup()`を使うように状態を戻して様子を見たいと思います

**Comment by orenomask** [comment]
packages.debian.orgで検索してみましたが
不具合修正版のバックポートパッケージ等も無いですね

ご対応に元報告者の900氏も喜ぶと思います
今回代理でご報告差し上げましたがユーザーの皆さんにgithubの活用が浸透するといいですね
人によっては利用に当たって不明点や不安要素もあるかと思われますので
今後可能な範囲でフォローして下されば有り難く思います

**Comment by orenomask** [comment]
今回の代行は最初で最後であり、私なりにこちらの利用ケースを残せればと思い行動させて頂きました
以後は皆様の自由な意思による参加で宜しいかと思う次第です
コテハンに抵抗無ければ大変便利な枠組みなので少しでも多くの方々に利用して頂けるといいですね

**Comment by ma8ma** [comment]
#987 で修正しました。1週間程度様子を見て問題が報告されなければissueを閉じたいと思います。

**Comment by ma8ma** [comment]
修正後、特に問題の報告がないため閉じます
レポートありがとうございました
